// Code generated by MockGen. DO NOT EDIT.
// Source: /home/alisson-arus/projects/ms-credit-score/internal/interfaces/redis.go

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	redis "github.com/gomodule/redigo/redis"
)

// MockIRedisClient is a mock of IRedisClient interface.
type MockIRedisClient struct {
	ctrl     *gomock.Controller
	recorder *MockIRedisClientMockRecorder
}

// MockIRedisClientMockRecorder is the mock recorder for MockIRedisClient.
type MockIRedisClientMockRecorder struct {
	mock *MockIRedisClient
}

// NewMockIRedisClient creates a new mock instance.
func NewMockIRedisClient(ctrl *gomock.Controller) *MockIRedisClient {
	mock := &MockIRedisClient{ctrl: ctrl}
	mock.recorder = &MockIRedisClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRedisClient) EXPECT() *MockIRedisClientMockRecorder {
	return m.recorder
}

// Client mocks base method.
func (m *MockIRedisClient) Client() redis.Conn {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Client")
	ret0, _ := ret[0].(redis.Conn)
	return ret0
}

// Client indicates an expected call of Client.
func (mr *MockIRedisClientMockRecorder) Client() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Client", reflect.TypeOf((*MockIRedisClient)(nil).Client))
}

// ConnCheck mocks base method.
func (m *MockIRedisClient) ConnCheck() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnCheck")
	ret0, _ := ret[0].(error)
	return ret0
}

// ConnCheck indicates an expected call of ConnCheck.
func (mr *MockIRedisClientMockRecorder) ConnCheck() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnCheck", reflect.TypeOf((*MockIRedisClient)(nil).ConnCheck))
}

// Get mocks base method.
func (m *MockIRedisClient) Get(key string, v any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", key, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockIRedisClientMockRecorder) Get(key, v interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockIRedisClient)(nil).Get), key, v)
}

// Set mocks base method.
func (m *MockIRedisClient) Set(key string, v any, exp int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", key, v, exp)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockIRedisClientMockRecorder) Set(key, v, exp interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockIRedisClient)(nil).Set), key, v, exp)
}
